


sudo: required
services:
  - docker

before_install:
  - docker build -t serefz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run serefz/react-test npm test -- --coverage

after_success:
  - docker build -t rfw62/multi-client ./client
  - docker build -t rfw62/multi-nginx ./nginx
  - docker build -t rfw62/multi-server ./server
  - docker build -t rfw62/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  # Take each build image and push them to dockerhub.com
  - docker push rfw62/multi-client
  - docker push rfw62/multi-nginx
  - docker push rfw62/multi-server
  - docker push rfw62/multi-worker

